version: 2.1

executors:
  aws-executor:
    docker:
      - image: amazon/aws-cli

commands:
  destroy_environment:
    steps:
      - run:
          name: Rollback network resources
          command: |
            aws cloudformation delete-stack --stack-name main-network-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail

jobs:
  build_aws_infra:
    executor: aws-executor
    steps:
      - run:
          name: Test backend
          command: |
            echo 'IaC everywhere!!'
      - destroy_environment

workflows:
  my_workflow:
    jobs:
      - build_aws_infra
