version: 2.1

jobs:
  print_hello:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: |
          node --version
          echo "hello"

  print_world:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: |
          echo "world"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
