version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2022.06

commands:
  print_pipeline_id:
    description: "A command to print CIRCLE_WORKFLOW_ID"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    executor: my-executor
    steps:
      - run: mkdir -p /tmp/workspace
      - run: echo "hello world" > /tmp/workspace/output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - print_pipeline_id
      - run: |
          cat /tmp/workspace/output.txt
          echo "project git url: " << pipeline.project.git_url >>

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  save-print-hello-workflow:
    jobs:
      - print_pipeline_id
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]
