version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2022.06
    steps:
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2022.06
    steps:
      - attach_workspace:
          at: /tmp/workspace
      run: |
        cat output.txt
        echo "project git url: " << pipeline.project.git_url >>

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  save-print-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]
